version: "3.8"
services: 
  mongodb:
    image: "mongo"
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      
  backend:
    build: "./backend"
    ports:
      - 9000:9000
    volumes:
      - ./backend:/app
      - /app/modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
      build: "./frontend"
      ports:
        - 8500:8500
      volumes:
        - ./frontend/src/:/app/src
      env_file:
        - ./env/frontend.env
      depends_on:
        - mongodb
        - backend

    
volumes:
  data:
    
  